import type { NextPage } from "next"
import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import {
  TelegramIcon,
  TelegramShareButton,
  TwitterIcon,
  TwitterShareButton,
  WhatsappIcon,
  WhatsappShareButton,
} from "next-share"
import { handleCopyLink, handleSaveImage } from "../service/handle-click"
import { handleWallet } from "../service/wallet"

import sampleImage from "../public/sample-image.png"

const generatedMessage =
  "Lihat [event_name]: [ticket_name] milik [user_full_name] sekarang [public_collection_detail_url] di "
const generatedUrl = "https://bolafy.com"

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center my-10 text-center">
        <h1 className="text-6xl">Bolafy Share Button</h1>
      </div>
      <div>
        <img id="image" src={sampleImage.src} alt="" crossOrigin="anonymous" />
      </div>
      <div className="flex justify-center content-center bg-green-200 mt-5 p-4 gap-2">
        <TwitterShareButton url={generatedUrl} title={generatedMessage}>
          <TwitterIcon size={32} round />
        </TwitterShareButton>
        <WhatsappShareButton
          url={generatedUrl}
          title={generatedMessage}
          separator=" "
        >
          <WhatsappIcon size={32} round />
        </WhatsappShareButton>

        <TelegramShareButton url={generatedUrl} title={generatedMessage}>
          <TelegramIcon size={32} round />
        </TelegramShareButton>
      </div>
      <div className="flex justify-center my-5 gap-2">
        <a>
          <button
            className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
            onClick={handleWallet}
          >
            Wallet
          </button>
        </a>
        <a>
          <button
            className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
            onClick={() => handleCopyLink()}
          >
            Copy Link
          </button>
        </a>
        <a>
          <button
            className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
            onClick={() => handleSaveImage()}
          >
            Save Image
          </button>
        </a>
      </div>
    </div>
  )
}

export default Home
